Use UrlGenerator in place of extracting the url from request
flarum/tags pull request #122
Opened 2021-03-08 14:51 UTC by imorland

Part 2 of https://github.com/flarum/core/issues/2673

2021-03-08 16:23 UTC, askvortsov1 requested changes

2021-03-08 16:23 UTC, askvortsov1 commented on src/Content/Tags.php
> +        $document->canonicalUrl = $defaultRoute === '/tags' ? $this->url->to('forum')->base() : $this->url->to('forum')->base().$request->getUri()->getPath();
`$this->url->to('forum')->base()` is duplicated. Maybe something like `$this->url->to('forum')->base().($defaultRoute === '/tags' ? '' : $request->getUri()->getPath()`?

2021-03-08 17:28 UTC, askvortsov1 approved these changes

2021-03-09 14:02 UTC, tankerkiller125 approved these changes

2021-03-16 01:44 UTC, merged