Optimize tag permissions
flarum/tags pull request #126
Opened 2021-04-24 04:11 UTC by askvortsov1

Currently, to check the tags where users have permissions, we:

- Pull in all tags
- Make a big array of all tags
- Send it back to the DB for a `whereIn`.

This is quite slow. Instead of doing this, this PR creates a subquery for all tags where a user has a permission, then feeds that subquery to `whereIn`s. Combined with #87, this makes a setup with:

- 50 top level primary tags
- 500 primary subtags distributed among the 50
- 3000 secondary tags

have negligible effects on initial page load.

2021-04-29 20:23 UTC, SychO9 requested changes
I still need to look into the new query, but here are a few initial comments

2021-04-29 20:23 UTC, SychO9 commented on src/Tag.php
> +    protected static function buildPermissionSubquery($base, $isAdmin, $hasGlobalPermission, $tagIdsWithPermission)
can we type hint these static methods ?

2021-05-03 23:24 UTC, tankerkiller125 approved these changes
Testing locally everything seems to be working OK

2021-05-04 15:16 UTC, SychO9 reviewed
Query looks good as far as I can tell.

2021-05-04 16:10 UTC, tankerkiller125 commented on src/Tag.php
> +        $allPermissions = $user->getPermissions();
Caching permissions can be difficult to handle correctly, but I agree that because of things like this it would be ideal with we could cache it.

2021-05-04 16:11 UTC, askvortsov1 commented on src/Tag.php
> +    protected static function queryIdsWhereCan(QueryBuilder $base, User $user, string $currPermission, bool $includePrimary = true, bool $includeSecondary = true): QueryBuilder
Wait, what? How on earth is this working now...

2021-05-04 16:14 UTC, SychO9 commented on src/Tag.php
> +        $allPermissions = $user->getPermissions();
we already do cache permissions, but it's a protected property of the user model. We'd just need to add a public method that allows accessing the property in core.

2021-05-04 16:16 UTC, askvortsov1 commented on src/Tag.php
> +        $allPermissions = $user->getPermissions();
I don't think caching permissions is the responsibility of Tags. In fact, in core, there is caching, it's just poorly implemented to only cover the `hasPermision` method. https://github.com/flarum/core/blob/77a8fc805914acbc05e7b284ff4ce5d2ec256157/src/User/User.php#L382-L384

I'll submit a PR to move that logic to the getPermission method.

2021-05-04 16:16 UTC, SychO9 commented on src/Tag.php
> +    protected static function queryIdsWhereCan(QueryBuilder $base, User $user, string $currPermission, bool $includePrimary = true, bool $includeSecondary = true): QueryBuilder
idk.. I found the fact that it still worked weird, I'm not sure if I'm missing something here about how calling static methods work, but it's a first for me.

2021-05-04 16:28 UTC, askvortsov1 commented on src/Tag.php
> +        $allPermissions = $user->getPermissions();
https://github.com/flarum/core/pull/2832

2021-05-04 16:37 UTC, SychO9 approved these changes

2021-05-04 16:53 UTC, merged