Initial tag load performance improvement
flarum/tags pull request #87
Opened 2020-06-29 11:01 UTC by luceos

### Current situation

On hitting the Forum index, the ShowForumController gets its payload enriched from `flarum/tags`:

https://github.com/flarum/tags/blob/164d67b23ba2b43e9146cc8c5eb1f8673cb956e3/src/Listener/AddForumTagsRelationship.php#L53-L56

This code loads **all tags** and some of its relations. For small forums this isn't really an issue. But forums that have a ton of subtags this affects performance. 

### New situation

I've decided to exclude subtags, but include helper tags. The helper tags are limited to three, unless you click "more tags" which redirects you to the tags page. We could potentially improve this logic further by only including the 3 tags with the most discussions (`withCount('discussions')`), but that would need some optimalization as subqueries can't use `limit` in MySQL.

I am currently deploying this branch to the Bokt staging environment.

2020-06-29 12:58 UTC, tankerkiller125 commented
I'm assuming that on clicking a parent tag the child tags will get loaded in? (I haven't had time to test locally)

2020-06-29 14:16 UTC, datitisev commented
This is definitely not ready for merge. When clicking on a tag, only those with existing discussions that load appear (because they are included in the /api/discussions response - we could improve performance times by *not* including already-loaded tags in API response, not sure if possible).

Sometimes a second child tag appears under another tag - not sure why that one is loaded 🤔.

2020-06-29 14:24 UTC, askvortsov1 commented
Iirc, there isn't currently a call to the tags endpoint in the tags frontend (at least not on the tags page I think)? How are additional tags being loaded?

Also, I'm still confused why the tag states can't be loaded alongside the tags themselves in a single query. I'm in favor of not loading everything at once for reasons of scalability and reducing payload size, but I think the multiple queries thing is the bigger issue when it comes to performance. Does it still occur when no extensions other than core and tags are enabled?

2020-06-29 14:25 UTC, datitisev commented
@askvortsov1 Additional tags are only loaded when a discussion has the tag.

2020-06-29 14:50 UTC, luceos commented
Hm, right I didn't look far enough beyond the first page. Will look into that.

2020-06-29 14:57 UTC, askvortsov1 commented
Also, if the page we're on IS the page for a parent tag (which is possible via custom homepages), perhaps we should load those too?

2020-06-29 15:22 UTC, datitisev commented
@askvortsov1 Well it'd also be a parent tag if you directly visit /t/<id>. I think this should also be extensible.

2020-07-20 10:18 UTC, luceos commented
@datitisev what exactly do you mean with extensible? What should be extensible?

2020-07-20 13:16 UTC, datitisev commented
@luceos 🤔 i don't know.

I assume deciding which tags get loaded, because of this comment I was replying to:
> Also, if the page we're on IS the page for a parent tag (which is possible via custom homepages), perhaps we should load those too?

2020-07-20 14:00 UTC, luceos commented
My pr adds a ShowTagController to load one tag through the api. The parent include (relation) already existed, I've added `children` in addition. There are a ton of other changes and I still need to tackle some minor things (like the permission grid tag selection). Other than that, it seems to already work much better than before.

2021-04-22 05:34 UTC, askvortsov1 commented
TODO: Add tag loading logic for the composer and selection modal.

I feel like this could also use pagination, but I think that might be better in a separate PR after we get @datitisev's PaginatedList utils class merged.

2021-04-22 22:06 UTC, askvortsov1 approved these changes

2021-04-23 04:24 UTC, askvortsov1 commented
Current setup:

~50 top level primary tags
~25 primary subtags for first 20 top level primary tags
~3000 secondary tags

Load differences:

- On a regular discussion page: ~5.1s => 2.2s
- On the discussion list: ~5s => 1.7s
- On a top-level primary tag page (with 25 children): ~5s => ~2.2s
- On a child tag page (with 25 siblings): ~5s => ~2.2s
- On the "all tags" page: ~4.9s => 5.1s

This still feels way too slow, especially the regular discussion / discussion list pages (with no tags, they load in ~200ms).

Also, some logic issues are still present with load. Taking this back into draft mode.

2021-04-24 05:31 UTC, askvortsov1 commented
And back out of draft

2021-05-04 16:01 UTC, SychO9 requested changes

2021-05-04 16:01 UTC, SychO9 commented on js/src/forum/states/TagListState.js
> +            .find('tags', { include: 'parent,lastPostedDiscussion' })
question: we technically also load the last posted discussion of secondary tags right ?

2021-05-04 16:08 UTC, tankerkiller125 commented on src/Api/Controller/ListTagsController.php
> +        'state'
I think this is a great idea, the less queries the better generally.

2021-05-04 16:18 UTC, askvortsov1 commented on src/Api/Controller/ListTagsController.php
> +        'state'
Ah, excellent!

2021-05-04 16:20 UTC, askvortsov1 commented on js/src/forum/states/TagListState.js
> +            .find('tags', { include: 'parent,lastPostedDiscussion' })
Currently yes. When the paginated list PR is merged, I'd like to update this so that it makes 2 queries: one for ALL the primary tags, and a paginated one for the secondary tags. That way, we could easily scale up to tens of thousands of secondary tags.

2021-05-04 16:20 UTC, SychO9 commented on js/src/forum/states/TagListState.js
> +            .find('tags', { include: 'parent,lastPostedDiscussion' })
Great! thanks.

2021-05-04 16:30 UTC, SychO9 approved these changes
Looks good to me, nice work!

2021-05-04 17:48 UTC, tankerkiller125 approved these changes

2021-05-04 17:57 UTC, merged