Renamed TagWillBeSaved => Saving. Deprecated the old event.
flarum/tags pull request #92
Opened 2020-08-14 11:09 UTC by iPurpl3x

As discussed in #86, here is a PR for the Saving event that was previously named TagWillBeSaved but should be renamed to match the general convention.
Is the `@deprecated beta 14, removed beta 15.` comment that I made right @askvortsov1 ?

2020-09-25 09:12 UTC, franzliedke requested changes

2020-09-25 09:12 UTC, franzliedke commented on src/Event/TagWillBeSaved.php
> + */
If we keep this, we would need to keep raising it as well.

Alternative (and my preference): Just remove the event. :wink:

2020-09-25 09:13 UTC, franzliedke commented on src/Event/TagWillBeSaved.php
> + */
Pretty much what Clark said, sorry.

2020-09-25 09:14 UTC, franzliedke commented on src/Event/TagWillBeSaved.php
> + */
Option 1 was actually requested by @askvortsov1 in https://github.com/flarum/tags/pull/86#issuecomment-646032898 as well.

2020-09-28 09:25 UTC, luceos commented
Looking at the discussion this is what still has to be done:

- [ ] Keep firing the deprecated event
- [ ] Create a new issue to remove that deprecated event and assign it to the next release/milestone 

@iPurpl3x could you tackle this so that we can ship it with the upcoming release?

@clarkwinkelmann let's create an issue for that, I think we need to make this a convention anyhow. We can then handle this in a new PR across all core extensions.

2020-10-02 16:55 UTC, merged